#! unieinfra.resource: 600GiB
version: '3.8'
services:
  unieinfra:
    image: registry.unieai.com/unieverse/uifw-one:latest
    volumes:
      # - "./weight:/weight"
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/unieai:/etc/unieai:ro
    tmpfs:
      - /cache/hf
    cap_add:
      - SYS_ADMIN
    runtime: nvidia
    environment:
    - NCCL_DEBUG=INFO
    - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    - HF_HOME=/cache/hf
    - HUGGINGFACE_HUB_CACHE=/cache/hf/hub
    shm_size: 256gb
    command: [with-u010, uifw, serve, api_server, meta-llama/Llama-3.1-70B-Instruct, --server-port,
      '35640', --log-level, INFO, --model-name, Llama-3.1-70B-Instruct, --session-len,
      '1024', --dtype, float16, --cache-max-entry-count, '0.1', --tp, '8']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
