version: '3.8'
services:
  unieinfra:
    #! resource: 24GiB
    image: registry.unieai.com/unieverse-private/uifw2.cuda.s.048
    volumes:
    - "./weight:/weight"
    ports:
    - 35640:35640
    runtime: nvidia
    environment:
    - NCCL_SHM_DISABLE=1
    - NCCL_DEBUG=INFO
    - CUDA_VISIBLE_DEVICES=0
    - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    shm_size: 32gb
    entrypoint: uifw
    command: [serve, api_server, meta-llama/Llama-3.1-8B-Instruct, --server-port,
      '35640', --log-level, INFO, --model-name, Llama-3.1-8B-Instruct, --session-len,
      '1024', --dtype, float16, --cache-max-entry-count, '0.1']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
