services:
  unieinfra:
    image: registry.unieai.com/unieverse-private/uifw2.cuda.l.064
    volumes:
      - "./weight:/weight"
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/unieai:/etc/unieai
    runtime: nvidia
    cap_add:
      - SYS_ADMIN
    environment:
      - NCCL_DEBUG=INFO
      - CUDA_VISIBLE_DEVICES=0
    shm_size: 256gb
    entrypoint: uifw
    command: serve api_server Qwen/Qwen2-0.5B-Instruct --backend=turbomind --tp=1  --server-port=8910 --model-name=Qwen2-0.5B-Instruct --enable-prefix-caching --chat-template=mixtral
