#! unieinfra.resource: 50GiB
version: '3.8'
services:
  unieinfra:
    image: vllm/vllm-openai:68179e5
    runtime: habana
    # environment:
      # - HABANA_VISIBLE_DEVICES=1
      # - hw=HL-325L
    # volumes:
    #   - /data1/models:/models
    entrypoint: vllm
    command: [serve, meta-llama/Meta-Llama-3-8B-Instruct, --port, '8000', --host, 0.0.0.0,
      --tensor-parallel-size, '1', --served-model-name, vLLM/Llama-3.1-8B-Instruct]