[variables]
main_domain = "${domain}"
template_type = "model"

[config]
env = [
  "TEMPLATE_TYPE=${template_type}",
  "HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}"
]
mounts = []

[[config.domains]]
serviceName = "unieinfra"
port = 8000
host = "${main_domain}"