#! unieinfra.resource: 50GiB
version: '3.8'
services:
  unieinfra:
    image: vllm/vllm-openai:v0.9.1
    volumes:
    - "./weight:/weight"
    runtime: nvidia
    environment:
    - NCCL_DEBUG=INFO
    shm_size: 32gb
    entrypoint: vllm
    command: [serve, Qwen/Qwen3-30B-A3B,
              --port, '8910',
              --host, 0.0.0.0,
              --tensor-parallel-size, '1',
              --served-model-name, Qwen3-30B-A3B,
              --trust_remote_code,
              --enable-prefix-caching]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
