#! unieinfra.resource: 50GiB
version: '3.8'
services:
  unieinfra:
    image: vllm/vllm-openai:68179e5
    runtime: habana
    # environment:
    #   - HABANA_VISIBLE_DEVICES=1
    #   - hw=HL-325L
    # volumes:
    #   - /data1/models:/models
    entrypoint: vllm
    command: [serve, mistral/Mixtral-8x7B-Instruct-v0.1, --port, '8000', --host, 0.0.0.0,
      --tensor-parallel-size, '1', --served-model-name, vLLM/Mixtral-8x7B-Instruct-v0.1]