x-registries:
  dockerhub:
    name: docker.io
    username: nctu6
    password: ${DOCKERHUB_PWD}
services:                                                                                                              
  worker-1:                                                                                                            
    image: nctu6/uifw2
    volumes:                                                                                                           
      - "./weight:/weight"                                                                                             
    ports:                                                                                                             
      - 35640:35640                                                                                                    
    environment:                                                                                                       
      CUDA_VISIBLE_DEVICES: "0"                                                                                        
    #entrypoint: sleep                                                                                                 
    #command: ["36000"]                                                                                                
    entrypoint: uifw                                                                                                   
    command: ["serve", "api_server", "Qwen/Qwen2.5-0.5B-Instruct", "--log-level", "INFO", "--model-name", "Qwen2.5-0.5B-Instruct", "--eager-mode", "--cache-max-entry-count", "0.4", "--enable-prefix-caching", "--chat-template", "qwen2d5", "--dt
ype", "float16", "--session-len", "16384"]                                                                            
    deploy:                                                                                                            
      resources:                                                                                                       
        reservations:                                                                                                  
          devices:                                                                                                     
            - driver: nvidia                                                                                           
              device_ids: ["0"]                                                                                        
              capabilities: [gpu]                                                                                      