#! unieinfra.resource: 300GiB
version: '3.8'
services:
  unieinfra:
    image: registry.unieai.com/unieverse-temp/uifw-one-2e3075d:latest
    volumes:
    - "./weight:/weight"
    runtime: nvidia
    environment:
    - NCCL_SHM_DISABLE=1
    - NCCL_DEBUG=INFO
    - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    shm_size: 80gb
    command: [with-u010, uifw, serve, api_server, mistralai/Mixtral-8x7B-Instruct-v0.1, --server-port,
      '35640', --log-level, INFO, --model-name, Mixtral-8x7B-Instruct-v0.1, --session-len,
      '1024', --dtype, float16, --cache-max-entry-count, '0.1', --tp, '4']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
