version: "3.8"

services:
  unieinfra:
    image: vllm/vllm-openai:latest
    runtime: nvidia  # Required for GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "8000"
    environment:
      - NCCL_SHM_DISABLE=1  # Bypass shared memory transport
      - NCCL_DEBUG=INFO  # Enable detailed error logging
    shm_size: "8gb"
    entrypoint: vllm
    command: ["serve", "microsoft/Phi-3-medium-4k-instruct", "--served-model-name", "Phi_3_medium_4k_instruct"]
