[variables]
main_domain = "${domain}"

[config]
env = []
mounts = []

[[config.domains]]
serviceName = "unieinfra"
port = 35640
host = "${main_domain}"

[config.env]
HUGGING_FACE_HUB_TOKEN="${HUGGING_FACE_HUB_TOKEN}"
