#! unieinfra.resource: 50GiB
version: '3.8'
services:
  unieinfra:
    image: registry.unieai.com/unieverse-temp/uifw-one-2e3075d:latest
    volumes:
    - "./weight:/weight"
    runtime: nvidia
    environment:
    # - NCCL_SHM_DISABLE=1
    - NCCL_DEBUG=INFO
    shm_size: 32gb
    command: [with-u010, uifw, serve, api_server, Qwen/Qwen3-30B-A3B, --server-port,
      '35640', --log-level, INFO, --model-name, Qwen3-30B-A3B, --session-len,
      '1024', --dtype, float16, --cache-max-entry-count, '0.1']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
