#! unieinfra.resource: 75GiB
version: '3.8'
services:
  unieinfra:
    image: vllm/vllm-openai:v0.9.1
    volumes:
    - "./weight:/weight"
    runtime: nvidia
    environment:
    - NCCL_DEBUG=INFO
    - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    shm_size: 32gb
    entrypoint: vllm
    command: [serve, meta-llama/Llama-3.1-8B-Instruct,
              --port, '8910',
              --host, 0.0.0.0,
              --tensor-parallel-size, '1',
              --served-model-name, Llama-3.1-8B-Instruct,
              --trust_remote_code,
              --enable-prefix-caching]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
