#! unieinfra.resource: 150GiB
version: '3.8'
services:
  unieinfra:
    image: vllm/vllm-openai:v0.9.1
    volumes:
    - "./weight:/weight"
    runtime: nvidia
    environment:
    - NCCL_DEBUG=INFO
    - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    - "/data/weights/meta-llama/Llama-3.2-11B-Vision-Instruct/chat_template.jinja:/app/chat_template.jinja"
    shm_size: 128gb
    entrypoint: vllm
    command: [serve, "meta-llama/Llama-3.2-11B-Vision",
          "--port", "8910",
          "--host", "0.0.0.0",
          "--tensor-parallel-size=2",
          "--limit-mm-per-prompt=image=1,video=1",
          "--served-model-name=Llama-3.2-11B-Vision",
          "--trust_remote_code",
          "--max-model-len=32768",
          "--max-num-seqs=128",
          "--chat-template=/app/chat_template.jinja"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
            - gpu
